@startuml Board_Game_Cafe_System_Class_Diagram
skinparam classAttributeIconSize 0

title Board Game Cafe System Class Diagram

' ==========================================

package "Management Core" {
    class CafeSystem {
        - person : List<Person>
        - cafe_branches : List<CafeBranch>
        - reservations : List<Reservation>
        - simulated_time : datetime

        + get_time() : datetime
        + set_simulated_time(time_str)
        + add_person(person)
        + create_owner(name, requester_id=None)
        + create_manager(name, requester_id=None)
        + create_staff(name, requester_id=None)
        + create_customer_member(name)
        + create_customer_walk_in()
        + add_owner_to_branch(branch_id, owner_id, requester_id=None)
        + add_manager_to_branch(branch_id, manager_id, requester_id=None)
        + add_staff_to_branch(branch_id, staff_id, requester_id=None)
        + get_person()
        + get_person_by_type(person_type)
        + find_person_by_id(user_id)
        + find_person_by_name(name)
        + remove_person_by_id(user_id, requester_id=None)
        + update_person_by_id(user_id, name, requester_id=None)
        + add_spent(customer_id, amount)
        + create_cafe_branch(cafe_branch_name, cafe_branch_location="", requester_id=None)
        + get_cafe_branches()
        + find_cafe_branch_by_id(_id)
        + find_cafe_branch_by_name(name)
        + remove_cafe_branch_by_id(cafe_branch_id, requester_id=None)
        + update_cafe_branch_by_id(branch_id, name, location, requester_id=None)
        + make_reservation(customer_id, branch_id, total_player, date, start_time, end_time, table_id="auto")
        + add_reservation(reservation)
        + get_reservations()
        + find_reservation_by_id(reservation_id)
        + remove_reservation_by_id(reservation_id)
        + cancel_reservation(reservation_id, current_time=None)
        + update_reservation_status_by_id(reservation_id, status)
        + set_reservation_cancel_by_id(reservation_id)
        + set_reservation_no_show_by_id(reservation_id)
        + set_reservation_complete_by_id(reservation_id)
        + create_table_to_branch(branch_id, capacity, requester_id=None)
        + get_branch_tables(branch_id)
        + update_reserved_tables()
        + search_available_table(branch_id, required_capacity=0)
        + update_table_status(table_id, status)
        + create_board_game_to_branch(branch_id, name, genre, price, min_players, max_players, description="", requester_id=None)
        + get_branch_board_games(branch_id)
        + find_board_game_by_id(board_game_id)
        + search_board_game_by_min_players(branch_id, min_players)
        + search_board_game_by_max_players(branch_id, max_players)
        + update_board_game_status(board_game_id, status)
        + remove_board_game_by_id(board_game_id, requester_id=None)
        + create_menu_to_branch(branch_id)
        + create_menu_item_food_to_branch(branch_id, name, price, description="", requester_id=None)
        + create_menu_item_drink_to_branch(branch_id, name, price, cup_size, description="", requester_id=None)
        + get_branch_menu(branch_id)
        + get_branch_menu_item(branch_id)
        + get_branch_menu_item_food(branch_id)
        + get_branch_menu_item_drink(branch_id)
        + find_menu_item_by_id(menu_item_id)
        + remove_menu_item_by_id(menu_item_id, requester_id=None)
        + update_menu_item_by_id(menu_item_id, name, price, description="", requester_id=None)
        + check_in_reserved(reservation_id, customer_id, current_time=None)
        + check_in(branch_id, player_amount, customer_id="walk_in", table_id="auto", start_time=None)
        + join_session(any_id, customer_id="walk_in")
        + borrow_board_game(any_id, board_game_id, current_time=None)
        + return_board_game(any_id, board_game_id, is_damaged=False)
        + maintenance_board_game(board_game_id, requester_id=None)
        + take_order(any_id, menu_item_id, current_time=None)
        + get_play_session_orders(any_id)
        + update_order(play_session_id, order_id, session_status)
        + update_order_preparing(play_session_id, order_id)
        + update_order_serve(play_session_id, order_id)
        + update_order_cancel(play_session_id, order_id)
        + check_out(any_id, method_type="cash", end_time=None, **kwargs)
        + create_payment(total, method_type="cash", **kwargs)
        + get_active_bill(session_id, current_time=None)
        + bill_history(session_id)
        + bill_history_by_person(person_id)
        + find_play_session_by_id(any_id)
        + find_play_session_history_by_id(any_id)
        + auto_force_checkout(session_id, staff_id, method_type="cash", current_time=None, **kwargs)
        - __authorize(requester_id, allowed_roles)
    }

    class CafeBranch {
        - branch_id : str
        - name : str
        - location : str
        - tables : List<Table>
        - board_games : List<BoardGame>
        - menu_list : MenuList
        - staff_id : List<str>
        - manager_id : str
        - owner_id : str
        - play_sessions : List<PlaySession>
        - play_sessions_history : List<PlaySession>

        + total_tables : int
        + total_board_games : int
        + add_table(capacity)
        + get_tables()
        + find_table_by_id(table_id)
        + add_board_game(name, genre, price, min_players, max_players, description="")
        + get_board_games()
        + find_board_game_by_id(board_game_id)
        + search_board_game_by_min_players(min_players)
        + search_board_game_by_max_players(max_players)
        + remove_board_game_by_id(board_game_id)
        + create_menu(menu)
        + create_menu_item_food(name, price, description="")
        + create_menu_item_drink(name, price, cup_size="S", description="")
        + get_menu()
        + get_menu_item()
        + get_menu_item_food()
        + get_menu_item_drink()
        + find_menu_item_by_id(menu_item_id)
        + remove_menu_item_by_id(menu_item_id)
        + update_menu_item_by_id(menu_item_id, name, price, description="")
        + get_play_session_orders(any_id)
        + get_play_sessions_history()
        + add_play_session(play_session)
        + get_play_sessions()
        + find_play_session_by_id(any_id)
        + find_play_session_history_by_id(any_id)
        + remove_play_session_by_id(play_session_id)
        + end_play_session(play_session_id, end_time=None)
        + add_staff(staff)
        + get_staff()
        + remove_staff_by_id(staff_id)
        + add_manager(manager)
        + get_manager()
        + remove_manager()
        + add_owner(owner)
        + get_owner()
        + remove_owner()
    }
}

' ==========================================

package "Person & Auth" {
    abstract class Person {
        - name : str
        - user_id : str
    }

    class NonCustomer {
        - salary : float
    }

    class Manager {
        - {static} counter : int = 0
        - managed_branches : str
    }

    class Owner {
        - {static} counter : int = 0
        - owned_branches : List<str>
        + add_owned_branch(branch_id)
    }

    class Staff {
        - {static} counter : int = 0
        - assigned_branch : str
    }

    abstract class Customer {
        - phone_number : str
        - note : str
        - email : str

        + {abstract} get_total_spent()
        + {abstract} get_discount()
        + {abstract} get_member_tier()
    }

    enum MemberTier {
        NONE_TIER
        BRONZE
        SILVER
        GOLD
        PLATINUM
    }

    class Member {
        - {static} counter : int = 0
        - total_spent : float
        - member_tier : MemberTier
        - birth_date : str

        + get_total_spent()
        + get_member_tier() : MemberTier
        + update_member_tier()
        + get_discount() : float
    }

    class WalkInCustomer {
        - {static} counter : int = 0
        + get_total_spent()
        + get_member_tier() : MemberTier
        + get_discount() : float
    }
}

' ==========================================

package "Inventory & Menu" {

    enum OrderStatus {
        PENDING
        PREPARING
        SERVED
        CANCELLED
    }

    enum BoardGameStatus {
        AVAILABLE
        IN_USE
        MAINTENANCE
        UNAVAILABLE
    }

    class Order {
        - {static} counter : int = 0
        - order_id : str
        - menu_items : MenuItem
        - status : OrderStatus
        - snapshot_price : float
        - snapshot_name : str

        + get_price : float
        + set_order_status(status)
        + set_order_preparing()
        + set_order_serve()
        + set_order_cancel()
    }

    class MenuList {
        - menu_items : List<MenuItem>

        + add_menu_item(menu_item)
        + get_menu_item(item_id)
        + get_menu_item_food()
        + get_menu_item_drink()
        + get_menu_item_list()
        + find_menu_item_by_id(item_id)
        + remove_menu_item(item_id)
    }

    abstract class MenuItem {
        - item_id : str
        - name : str
        - price : float
        - is_available : bool
        - description : str
    }

    class Food {
    }

    class Drink {
        - cup_size : str
    }

    class BoardGame {
        - {static} counter : int = 0
        - board_game_id : str
        - name : str
        - genre : str
        - price : float
        - status : BoardGameStatus
        - min_players : int
        - max_players : int
        - description : str
    }
}

' ==========================================

package "Operations (Session & Reservation)" {

    enum TableStatus {
        AVAILABLE
        RESERVED
        OCCUPIED
        MAINTENANCE
    }

    class Table {
        - {static} counter : int = 0
        - table_id : str
        - capacity : int
        - status : TableStatus
        {static} + price_per_hour : int = 15
    }

    class Reservation {
        - {static} counter : int = 0
        - reservation_id : str
        - current_reservation_date : date
        - reservation_time : datetime
        - customer_id : str
        - branch_id : str
        - table_id : str
        - date : str
        - start_time : str
        - end_time : str
        - total_player : int
        - status : ReservationStatus
        - deposit : int

        + update_status(new_status)
        + to_dict()
    }

    enum ReservationStatus {
        PENDING
        CANCELLED
        COMPLETED
        NO_SHOW
    }

    class PlaySession {
        - {static} counter : int = 0
        - session_id : str
        - table_id : str
        - start_time : datetime
        - end_time : datetime
        - current_players_id : List<str>
        - current_board_games_id : List<str>
        - current_order : List<Order>
        - reservation_id : str
        - payment : Payment
        - game_penalty : List<Dict>
        - reserved_duration : int
        - reserved_end_time : datetime

        + add_players_id(player_id)
        + add_board_games_id(board_game_id)
        + add_game_penalty(game_id, price)
        + get_total_players() : int
        + take_order(menu_item) : Order
        + remove_board_games_id(board_game_id)
        + remove_players_id(player_id)
        + duration(current_time) : int
        + check_time_up(current_time) : bool
        + is_time_up : bool
    }
}

' ==========================================

package "Payment" {
    class Payment {
        - {static} counter : int = 0
        - payment_id : str
        - amount : float
        - payment_method : PaymentMethod
        - payment_time : datetime

        + process_payment : bool
    }

    abstract class PaymentMethod {
        - method_id : str

        + {abstract} validate_method()
    }

    class Cash {
        - {static} counter : int = 0
        - paid_amount : float
        - change : float

        + validate_method()
    }

    class CreditCard {
        - {static} counter : int = 0
        - card_number : str
        - expiry_date : str
        - cvv : str

        + validate_method()
    }

    class OnlinePayment {
        - {static} counter : int = 0
        - email : str

        + validate_method()
    }
}

' ==========================================
' --- Inheritance ---
Person <|-- NonCustomer
NonCustomer <|-- Manager
NonCustomer <|-- Staff
NonCustomer <|-- Owner
Person <|-- Customer
Customer <|-- Member
Customer <|-- WalkInCustomer

MenuItem <|-- Food
MenuItem <|-- Drink

PaymentMethod <|-- Cash
PaymentMethod <|-- CreditCard
PaymentMethod <|-- OnlinePayment

' --- Composition (lifecycle dependent) ---
CafeSystem "1" *--> "*" CafeBranch
CafeSystem "1" *--> "*" Person
CafeSystem "1" *--> "*" Reservation

CafeBranch "1" *--> "*" PlaySession
CafeBranch "1" *--> "*" BoardGame
CafeBranch "1" *--> "*" Table
CafeBranch "1" *--> "1" MenuList

PlaySession "1" *--> "*" Order
' PlaySession "1" *--> "*" GamePenalty (Implemented as List of Dict)

' --- Aggregation ---
MenuList "1" o--> "*" MenuItem

' --- Association ---
Manager "1" --> "0..1" CafeBranch : manages >
Owner "1" --> "*" CafeBranch : owns >
Staff "*" --> "0..1" CafeBranch : assigned to >

Reservation "*" --> "1" Customer : reserved by >
Reservation "*" --> "1" Table : reserves >
Reservation "*" --> "1" CafeBranch : booked at >

Payment "1" --> "1" PaymentMethod : paid via >
Order "*" --> "1" MenuItem : contains >

Member "*" --> "1" MemberTier : tiered as >

PlaySession "*" --> "1" Table : uses >
PlaySession "1" --> "0..1" Reservation : linked to >
PlaySession "1" --> "0..1" Payment : paid via >

' GamePenalty "*" --> "1" BoardGame : penalizes (Not a class)

@enduml
